/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kuaishou_kcode_CppHash */

#ifndef _Included_com_kuaishou_kcode_CppHash
#define _Included_com_kuaishou_kcode_CppHash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kuaishou_kcode_CppHash
 * Method:    get_hash
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kuaishou_kcode_CppHash_get_1hash
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
